### ISSUE TITLE
database error in subscriptions

### ISSUE THREAD

**Issue by grisu68** [jonjomckay/fritter#128]
Hello,

I have freshly install fritter.
It shows the trends, but under groups and subscriptions I see only some database errors.
![Screenshot_20210528_182020_com jonjomckay fritter](https://user-images.githubusercontent.com/60393097/120016296-ba102100-bfe4-11eb-98d4-f500b803e844.jpg)
![Screenshot_20210528_182030_com jonjomckay fritter](https://user-images.githubusercontent.com/60393097/120016354-c8f6d380-bfe4-11eb-917e-31376941a650.jpg)

What I am doing wrong?

**Comment by jonjomckay** [comment]
@grisu68 which version of Fritter are you running? This looks like the migration issue that was fixed in v2.6.2 (hopefully). I know F-Droid is lagging behind with the updates, but you can download the latest version directly from GitHub (or wait for the update to come in through F-Droid, if that's easier).

**Comment by grisu68** [comment]
I have removed 2.6.2 and installed 2.7.0. Now it is working. :)
