### ISSUE TITLE
searching twitter URLs with queries break search; "skip" empty results tab

### ISSUE THREAD

**Issue by elig0n** [jonjomckay/fritter#131]
URLs of the format:
https://twitter.com/USERNAME/status/STATUSID?s=20

(which I copied off the twitter main app via the Share button)
do not get recognized as twitter tweets and show up as search results.

A valid URL would be:
https://twitter.com/USERNAME/status/STATUSID

I suggest to implement a way to handle this automatically i.e. to strip unnecessary parameters/queries from the URL programmatically when searching.

Also, another suggestion: if there are only tweet search results but not profile/user results it would be better to automatically switch to the tweets search results tab, and vice-versa.

**Comment by jonjomckay** [comment]
Thanks for the bug report! The fix will be in v2.9.0.

>When launching Fritter from a Twitter URI in another application, if
Fritter is already open, the link appears to not open, as it replaced
a widget underneath the currently-shown one.
>
> This fixes the issue by always pushing a new navigation item on top of
what's already displayed. It does mean the navigation stack gets longer
(i.e. pressing back will progress through the stack instead of going
back to the calling app), but that's probably preferable to nothing
showing at all sweat_smile.
