### ISSUE TITLE
[BUG] Groups are not refreshed after creation/deletion

### ISSUE THREAD

**Issue by wijourdil** [jonjomckay/fritter#171]
**Describe the bug**

When I create a new group, the subscriptions page is not updated, the new group is not shown
Same thing when I delete an existing group, the deleted group is still visible on the subscriptions page

**To Reproduce**

1. (Re)start the app, and go to the subscriptions page
2. Click on new to add a new group
3. In the modam, give the group a name, and click OK
4. The modal closes, but the group is not shown

**Screenshots**

1. Page BEFORE creation
![Screenshot_20210619-211744_Fritter.png](https://user-images.githubusercontent.com/12596207/122653279-e92d3480-d143-11eb-9206-17dd514c30e6.png)

2. Modal 
![Screenshot_20210619-211805_Fritter.png](https://user-images.githubusercontent.com/12596207/122653308-10840180-d144-11eb-8027-0b27424dfb63.png)

3. Page AFTER creation
![Screenshot_20210619-211820_Fritter.png](https://user-images.githubusercontent.com/12596207/122653313-14178880-d144-11eb-9f4d-0cc16d550478.png)

4. Page AFTER creation and after app kill/reboot
![Screenshot_20210619-212030_Fritter.png](https://user-images.githubusercontent.com/12596207/122653375-4923db00-d144-11eb-82f9-79fd34462df8.png)

**Device**

Oneplus 6, LineageOS 18.1, Fritter 2.10

**Comment by jonjomckay** [comment]
This one was already fixed in v2.11.0 (#163), but it looks like that version still hasn't made its way through to F-Droid (it takes a few days, sometimes a week, for them to pick it up).

You can download the latest version from [GitHub Releases](https://github.com/jonjomckay/fritter/releases) for now, but make sure to export your subscriptions beforehand, as you'll need to uninstall the F-Droid version first!
