### ISSUE TITLE
Nitter

### ISSUE THREAD

**Issue by ghost** [jonjomckay/fritter#176]
Add Nitter instant of Twitter. It helps to get privacy little more.
Or add nitter extra addon.

**Comment by jonjomckay** [comment]
Could you give a little more detail on what exactly you're looking for?

Fritter did originally use Nitter as its source, but it was [removed in v2.0.0](https://github.com/jonjomckay/fritter/releases/tag/v2.0.0) due to the potential to accidentally DDOS instances, and every Nitter instance was running a different version, which made parsing extremely difficult.

**Comment by jonjomckay** [comment]
Closing, as the issue creator has deleted their account and there's been no reply.
