### ISSUE TITLE
[Feature Request] Hide Retweets and Replies in Groups and/or Globally.

### ISSUE THREAD

**Issue by alphanerdgen** [jonjomckay/fritter#24]
Original posts tend to get lost if a user RTs or replies a lot. Therefore an option to hide them will be useful.

**Comment by ceptonit** [comment]
I second this, especially the replies.
It makes group viewing exponentially longer to go through based on how active a tweeter user is with replies.

**Comment by jonjomckay** [comment]
Interesting idea, and one that could improve usability a lot. It could also make sense to display an icon or caption above a tweet to say it's a reply, and to also make the "replies" icon at the bottom tappable for tweets with replies, just so the context isn't removed.

**Comment by jonjomckay** [comment]
I've figured out how this can be achieved, but the only thing is that the Search API I'm using doesn't always return all the expected tweets... I suppose that's another, separate issue though, so I should be able to polish this off and ship it in the next release 😃

**Comment by alphanerdgen** [comment]
Not seeing any replies or retweets in my feed after updating the app to 2.3.2 so I guess you can close this issue now. 

Thanks for the great work! 👍

**Comment by WindHun7er** [comment]
I agree the answers are sometimes annoying in the timeline. But, on the other hand I personally have several groups where I would like to be able to see the retweets as well. 

When you subscribe to someone it's not necessarily to see their replies but I think you can accept that it's also to see what they retweet... 

So I don't know if this is possible but rather than taking away this possibility from the users why not let them choose ?

If this is possible It's probably more work for @jonjomckay (sorry) but I would find it more relevant...

**Comment by jonjomckay** [comment]
@alphanerdgen I don't think that was something I did - it's probably the Search API just not returning those tweets now. The PR for this issue (#71) will address the comments here by providing an option on subscription groups to enable or disable replies and retweets, but it'll only work on the tweets that actually get returned in the current method I'm using to list the tweets, which doesn't show everything.

I plan to tackle that in another issue, as it probably requires a complete overhaul of how subscription group feeds are constructed.
