### ISSUE TITLE
Issue with Hashtags

### ISSUE THREAD

**Issue by alphanerdgen** [jonjomckay/fritter#25]
**What Happens**: Tapping on a hashtag merely brings up the keyboard with the cursor blinking at the end of the hashtag in the search box.

**What Should Happen**: Tapping on a hashtag should immediately show the hashtagged tweets instead.

Android Version: 11
App Version: 2.0.0
Repo: F-Droid

**Comment by jonjomckay** [comment]
Yes, I've already tried to fix this one but it requires a bit more work. It's using Flutter's `SearchDelegate` widget, but that widget doesn't provide a way to supply a query **and** start the search.

It might be possible by tricking it into displaying the results as autocomplete suggestions, but it'll need to be debounced otherwise it'll send a request for every key tap...

I'll investigate 🕵🏽‍♂️
