### ISSUE TITLE
[BUG] Some retweets disappear in Feed

### ISSUE THREAD

**Issue by Philate** [jonjomckay/fritter#288]
> Please make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

**Describe the bug**

Retweets **without any comment** don't show up in "Feed".
Retweets with comment are normally displayed in "Feed".
Thanks. Guess it's caused by certain API ? 

**To Reproduce**

1. Check out "no comment" retweets in subscription tweets.
2. Look if those retweets appear in "Feed".

**Screenshots**
Feed versus Tweets
![comparison](https://user-images.githubusercontent.com/94914251/143052731-dd1d9efd-82b1-44ff-91ce-a04d92e43d30.png)

**Device**
Samsung Note 10
Android 10
Fritter v2.15.1

**Comment by cobratbq** [comment]
I have found that, in general, tweets are missing from the feed too. I suspect this issue is at the very least part of it, if not the whole issue. I also wonder if tweets are skipped if same account replies to its first tweet to make a thread. For reference, I have the issue that [this tweet](https://twitter.com/rivm/status/1472268917292912640) will not show up in my feed.

**Comment by jonjomckay** [comment]
Yes, this is a problem with the Twitter API that Fritter is using - it just doesn't return all tweets that match our query - mostly retweets are ignored. It's private, undocumented and unsupported by Twitter, so I don't think there's anything I can really do about it unfortunately.

I'll close this with regret as "wontfix" as it's not something that's in my control. This limitation is always at the back of my mind though, so be rest assured that if a solution appears in the future, Fritter will support it!
