### ISSUE TITLE
[BUG] Trouble updating the app

### ISSUE THREAD

**Issue by Gthbacc** [jonjomckay/fritter#316]
Glad you updated the app after a long time but the new update wont install due to incompatibility.
I first installed the app from f-droid and kept updating it from there. Apparently i installed a version (2.15.1) which is only compatible with arm64-v8a and I cant install any other version other than that.
I would happily uninstall and download the github version but I have a lot of tweets saved that I already have trouble accessing (I have opened a thread already).
Would it be possible for you to update the f-droid release compatible with my device? Perhaps the former error is fixed and i can get my data out successfully?
Thanks in advance.

**Comment by jonjomckay** [comment]
Unfortunately, due to some Android limitations, you're not able to upgrade from the F-Droid version to the GitHub version, as they're signed with different keystores. The only way you could do that is by exporting your data, uninstalling, installing the GitHub version, then re-importing your data (annoying, I know). Another solution is to use a root backup app to back up and restore the app data between uninstalling/installing, which also bypasses the Fritter import/export functionality. 

The v2.16 series will make it to F-Droid eventually, but it takes time for the PR to be merged, then F-Droid needs to build it (a few days), then it'll release in the next F-Droid release window (another few days).

I'll keep this open until you're able to try upgrading!

**Comment by Gthbacc** [comment]
Thanks for the response on here and the other thread. I'll wait for the f-droid release. Wouldnt mind a few more days. Thanks again.

**Comment by Gthbacc** [comment]
Got to update it to 2.16.0. I'll close this and keep updating #299. Thank you.
