### ISSUE TITLE
[BUG] Video playback issue

### ISSUE THREAD

**Issue by igorskyflyer** [jonjomckay/fritter#381]
**Describe the bug**
Fritter works great but there is an issue I am experiencing quite a lot. When I open a/any profile page with videos on it, for example I can only play (random) 2-3 videos out of 30+. The rest have an error placeholder in place of the video player, see screenshot. I am **NOT** experiencing video playback issues in any other application and clearing both the cache and the data of Fritter didn't help. Closing all applications doesn't help either - in case of video playback conflict.

**To Reproduce**
1. Go to any profile with several videos on feed
2. See error

**Screenshots**
![Screenshot_20220416-014451_Fritter_1](https://user-images.githubusercontent.com/20957750/163655959-c7f8a367-2de1-4c92-8047-e58641ffd2ac.png)

**Device**
Samsung A6+ (2018), Android 10, Fritter 2.16.3.

**Comment by jonjomckay** [comment]
This should now be fixed in 3.0.0-beta1, as videos are now only loaded when tapping to play. Previously, all tweets with videos were loading the player, but keeping it paused, causing some oddities in the underlying Java library with large numbers of loaded streams. This also has the bonus of using slightly less data, as it only displays the thumbnail, rather than loading the first frame(s) of the video as the thumbnail.
