### ISSUE TITLE
nsfw tweets not showing

### ISSUE THREAD

**Issue by KazutoKirigaya0** [jonjomckay/fritter#383]
how to reproduce
1. go to any account that makes nsfw tweets
2. theyre all gone

**Comment by jonjomckay** [comment]
This looks like it's because Twitter is geo-blocking NSFW tweets behind a login-wall in some countries. I'm not able to get around that unfortunately.

My advice would be to use a VPN, so it looks as if you're coming from another country (I recommend [Mullvad](https://mullvad.net/en/) as it's actually a privacy-friendly VPN run by trusted people).

Other than that, you could try another NSFW source 🙂
