### ISSUE TITLE
Wrong locale recognise

### ISSUE THREAD

**Issue by History-exe** [jonjomckay/fritter#384]
> Please make sure you've tried the [latest version](https://github.com/jonjomckay/fritter/releases) of Fritter first, as the F-Droid version is sometimes out of date!

**Describe the bug**
Locale is not en, but it recognised en. And no way to change

**To Reproduce**
1. Downloaded from F-drop
2. Open app, it should be my locale language interface, but it'is English, and the "say hello" also en

**Screenshots**

**Device**
device model: Oneplus7T pro
OS version: LineageOS17.1
device locale/language: zh-cn
Fritter version: 2.16.3

**Comment by jonjomckay** [comment]
I think this is because we only have translations for `zh-Hans`, as opposed to `zh-cn`. I'm not too familiar with the difference, but it would be appreciated if you could help add translations on our [Weblate project](https://hosted.weblate.org/projects/fritter/fritter)!

You should be able to log in with GitHub, copy `zh-Hans` (listed as Chinese (Simplified)) and make any changes there. I can then merge in support later on.
