### ISSUE TITLE
[REQ] Condensed & Text based minimalist layout

### ISSUE THREAD

**Issue by desmonk** [jonjomckay/fritter#407]
**Describe the problem that needs solving**
Right now, we can manage the size of media to save bandwidth, while the condensed and text only layout will help further improve readability and cost saving. This will also help incorporate more content in same window resulting in less scrolling with more content.

**Describe the solution you'd like**
Two layouts such as condensed and text based.

Thank you for your wonderful efforts!

**Comment by zopieux** [comment]
As an alternative to "layouts", a knob to choose tweet media size would be *very* welcome:

* full height (current behavior, AFAICT -- personally I find this unusable)
* medium (some reasonable value that is less than half/33% the device's screen height)
* small (some reasonable value that is less than 15% the device's screen height)
* none (text-focused)

Today this is a blocker for adopting Fritter as my go-to client. Thanks for your work on this otherwise super nice app!
