### ISSUE TITLE
[BUG] Interaction with images closes the app.

### ISSUE THREAD

**Issue by rsssxd** [jonjomckay/fritter#477]
https://user-images.githubusercontent.com/60405617/188746860-2124ea30-7bf1-4963-8a7a-0df286deffc6.mp4

https://user-images.githubusercontent.com/60405617/188746898-875140c5-0d7a-4a2d-a754-a4a1058c46eb.mp4

**Comment by jonjomckay** [comment]
I'm not able to reproduce this. Is this happening with 3.0.0-beta3?

**Comment by geominorai** [comment]
I can reproduce this and it seems similar to the one I posted on issue #444. I believe it's the swipe to close gesture activating on items in the feed instead of the image viewer.

It is easier to reproduce when swiping fast on the feed, since some of that gesture slips through the feed scrolling and ends up focusing on the image.

**Comment by SuNNjek** [comment]
Can also reproduce this in beta3. It seems like the swipe-up-to-close gesture also affects the previews in the feed

**Comment by geominorai** [comment]
I found an extremely reliable way to reproduce this issue in posts as well if there are almost no comments, thus not trigger scrolling when swiping.

https://user-images.githubusercontent.com/13911156/189501183-85959195-2c16-461f-b134-63f85ce59675.mp4

**Comment by jonjomckay** [comment]
It looks like this was caused by 82795fd62b959d66c05ccdebf35a429d942a871d accidentally being included inside an unrelated PR. I've fixed it up and pushed the change, so this should be working in the latest CI build, and the next beta build.
