### ISSUE TITLE
[BUG] Title bar text is invisible in true black theme

### ISSUE THREAD

**Issue by geominorai** [jonjomckay/fritter#508]
**Describe the bug**

The text on the title bar is black in true black, thus rendering it invisible. 

**To Reproduce**

1. Go to settings
2. Click on Theme
3. Toggle on True Black

**Screenshots**

<img src="https://user-images.githubusercontent.com/13911156/190882520-5d6779fd-4a38-4d69-9297-9ee26236b499.png" width=200 /> <img src="https://user-images.githubusercontent.com/13911156/190882524-8d148812-0181-4756-8709-e3c615fd9ca8.png" width=200 />

**Device**

Model: Samsung Galaxy S9+
OS: Android 10
Language: English
Fritter Version: v3.0.0-beta3+20220904

**Comment by Aga-C** [comment]
I confirm that bug is still in v3.0.0-beta4.

**Comment by johann-gambol** [comment]
Looks like, this bug is somehow connected to #521. 

The Textwidget for the `title` property of `FlexibleSpaceBar` won't get updated if the theme changes. If you remove the `FlexibleSpaceBar` and use the `title` property of `SliverAppBar`, the Textwidget updates on theme change. 

I removed the `FlexibleSpaceBar` for every screen in my pull-request #525. This should solve this problem also.

**Comment by Aga-C** [comment]
It's fixed in [v3.0.0-beta5](https://github.com/jonjomckay/fritter/releases/tag/v3.0.0-beta5).
