### ISSUE TITLE
[BUG] Swipe to the Subscriptions reloads the Feed

### ISSUE THREAD

**Issue by Solarunit** [jonjomckay/fritter#533]
**Describe the bug**

Swipe to the Subscriptions page and back to the Feed page reloads the Feed. Not sure if it's expected behavior.

Version: 3.0.0-beta3

**To Reproduce**
1. Swipe from the Feed page to the Subscriptions
2. Swipe back from the Subscriptions page to the Feed
3. Feed page will be reloaded

Version: 3.0.0-beta3

**Comment by Aga-C** [comment]
It's the same as https://github.com/jonjomckay/fritter/issues/434.

**Comment by geominorai** [comment]
Same goes for switching between any tab on a profile page.

Since the left/right swipe gesture to switch tabs is so sensitive, I often accidentally lose where I am after scrolling very deep down a feed and have to waste time scrolling back.

Now when I see it start switching tabs accidentally, I instantly panic and try to quickly swipe in the opposite direction before the tab switch animation finishes and disposes if the tab's contents. Seems like this is the only way to stop losing your scroll progress at the moment in this app.

**Comment by Solarunit** [comment]
>Since the left/right swipe gesture to switch tabs is so sensitive, I often accidentally lose where I am after scrolling very deep down a feed and have to waste time scrolling back, only to have it happen again a few seconds later.

Yea, happens very often for me. You also have to be especially careful when swiping pictures in the Feed.

**Comment by geominorai** [comment]
The saved posts feed still seems to be affected.

**Comment by geominorai** [comment]
Thanks!
