### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by login22rvp** [jonjomckay/fritter#60]
Is there any way in which i can use fritter on browser?
I wanted to use it on my laptop. If there are are any clients that can help do so then please let me know.
I don't want to use twitter directly as it requires login.

**Comment by dragonhunter056** [comment]
Do you mean something like Nitter.net?

**Comment by jonjomckay** [comment]
I think one of the [public Nitter instances](https://github.com/zedeus/nitter/wiki/Instances) might be your best shot for now. As far as I can tell Nitter doesn't currently support subscriptions, but you can maybe hack something around it with their RSS feeds?

It might be possible to build Fritter for the Web, using the stuff in Flutter v2.0 but I haven't tried it yet, although if it's anything like #55 then it might just work out of the box!

**Comment by login22rvp** [comment]
Nitter is good but if only we could have option to subscribe and then view the feed based on subscription.
Also having a webapp kind of make it device independent.

**Comment by iamtalhaasghar** [comment]
Setup Nitter RSS feeds for accounts you want to follow on a freemium/premium rss feeds service which supports all devices.
Or
Setup "tt-rss" tiny tiny rss on a server/computer/raspberry pi. You can then access your feess through a web login or any tt-rss client.

If you are privacy concious person then RSS feeds are great for you. You can use them to track youtube subscription as well. Using rss feeds from nitter you can follow public twitter and instagram accounts.

**Comment by login22rvp** [comment]
@iamtalhaasghar : thank you for detailed note. It helped.
I really liked Feedly, out of all the option suggested by you. 

I just wanted to know is Feedly a privacy focused solution. I do understand that it gives me an option to create a account only with email id (temp mail) so as such it feels safe.

**Comment by iamtalhaasghar** [comment]
I can't say anything about _Feedly_ because I have never used it. You can read their _Privacy Policy_ or look for reviews from other people on internet (may be on reddit, [alternativeto.net](https://alternativeto.net/software/feedly/about/) or any other privacy oriented forum). If you are asking for my opinion, I would rather setup my own feeds server or stick to standalone application because that way I would have control over my data.
After reading _Feedly's_ _Privacy Policy_, If you think, Feedly is not privacy friendly then you can search for privacy focused alternatives on [alternativeto.net](https://alternativeto.net/software/feedly/)

**Comment by login22rvp** [comment]
Thank you sharing alternative ans your opinion . I will explore.
