### ISSUE TITLE
Just for my own sanity - Is there no timeline functionality in the app?

### ISSUE THREAD

**Issue by vassijoseph** [jonjomckay/fritter#741]
As said in the title

As far as I can tell, this app has no timeline functionality to show the tweets of all my subscriptions in chronological order, right?

Am I missing something very obvious?

**Comment by j-fbriere** [comment]
It has been removed recently. Here is an [explanation why](https://github.com/jonjomckay/fritter/issues/668#issuecomment-1528784190) by the creator of the app.

Since then a fork of Fritter has been created with the functionality included in it.
It's called [Quacker](https://github.com/TheHCJ/Quacker).

**Comment by vassijoseph** [comment]
Okay, thanks for the response

Most of all what I wanted was to make sure I wasn't missing something
